### PR TITLE
[master < ] Fix segfault based on issue #874

### PR DESCRIPTION
**Pull request by DavIvek**
This PR is about handling queries in which we want to set a property of a null label, for example, `SET null.a = 1`. This type of query would cause a segmentation fault and would crash the database. To prevent this, QueryRunTimeException will be thrown.

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

@vpavicic

### CODE REVIEW

**Comment by gitbuda** [comment]
* the error string can be a bit more condensed/packed (smaller)
* in the error message user won't understand what an operator is (if it's not known from before), we should like this part of memgraph docs -> https://memgraph.com/docs/memgraph/reference-guide/inspecting-queries#operators (you should use the shortened link)

**Review by Ignition — COMMENTED** [review]
It would be nice to have better insight into the root cause.
This is a problem with operator creation.
`SetProperty` can handle null values at execution, for example `UNWIND [null] AS x SET x.a = 1` is fine. So what is it about construction of operators that has an issue with null literals for example `SET null.a = 1`?

**Comment by Josipmrden** [comment]
No comments from my side on the code except:
- branch name could be better (e.g. fix-crash-on-null-values-for-switch-case)
- Update the info for PR describing what is the fix about and on what query it works.

**Comment by DavIvek** [comment]
Even though throwing this exception isn't the solution to a problem with operator creation, it will prevent segmentation fault. We can leave issue #874 open and for mg-v2.12.0 find the root cause of the problem.

**Review by Ignition — APPROVED** [review]

**Pull request merged**
