### PR TITLE
Fix memory typo Alloc vs. Free

### PR DESCRIPTION
**Pull request by as51340**
[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by gitbuda** [comment]
Moved to v2.14 because we already started the v2.13 release process, @as51340 what's the impact of this? What's the worst thing that can happen?

**Comment by as51340** [comment]
> Moved to v2.14 because we already started the v2.13 release process, @as51340 what's the impact of this? What's the worst thing that can happen?

Not sure, I found this bug while I was searching for causes of stress test failing. Talked with @antoniofilipovic, he doesn't think it is too serious but he can expand here

**Comment by antoniofilipovic** [comment]
@gitbuda so, the impact of this is low. Jemalloc is not using commit hooks at all, I added that as part of "protection", but in any test locally they were not using commit hooks. 

This change only impacts the query memory tracker, so not a global tracker. But in any case, I think we can add TODO here to remove completely `commit` hooks.

**Review by antoniofilipovic — APPROVED** [review]

**Comment by antoniofilipovic** [comment]
@as51340 good find on this one :muscle:

**Pull request merged**
