### PR TITLE
Upgrade mgcxx to v0.0.7

### PR DESCRIPTION
**Pull request by gitbuda**
Upgrade mgcxx to v0.0.7 (github.com/memgraph/mgcxx#11)

Fixes the problem on the recent rustc compilers where the time library is not
compiling + upgrade to the latest stable Tantivi version (0.22.0)

### CODE REVIEW

**Comment by gitbuda** [comment]
### Tracking
- [ ] **[Link to Epic/Issue]**

### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch

### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_

### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

**Comment by gitbuda** [comment]
@MarkoBarisic before merging this, it's required to upgrade cargo/rustc to 1.75.0 or above.

**Comment by hal-eisen-MG** [comment]
cargo and rustc have been on 1.76 since at least the last mgbuilder run for the base image

**Review by MarkoBarisic — APPROVED** [review]
LGTM

**Pull request merged**
