### PR TITLE
[master < T1099] Add non-const mgp::Value return type for C++ API

### PR DESCRIPTION
**Pull request by mpintaric55334**
Using functions defined in mgp::Value, that return the Type of the value, such as ValueList, that extracted mgp::List from mgp::Value, only returned const types. While writing collections query module, there was need to return non const variables so move semantics could be used, this PR does exactly that.
[master < Task] PR
- [ ] Check, and update documentation if necessary
- [x] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [X] Write a release note here 
You are now able to extract non const data from mgp::Value @antoniofilipovic could you help me phrase this better, I dont think this is good.

- [X] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by mpintaric55334** [comment]
@antoniofilipovic can you help me phrase the description better. @vpavicic I will write the documentation when I get the green light and know how from Antonio.

**Review by antoniofilipovic — APPROVED** [review]
Looks good to go

**Comment by antoniofilipovic** [comment]
@mpintaric55334 @vpavicic for release note: Extend mgp::Value to return subtypes which are modifieable (non-const)

**Comment by vpavicic** [comment]
@mpintaric55334  C++ API?

**Pull request merged**
