### PR TITLE
Jemalloc use oversize threshold

### PR DESCRIPTION
**Pull request by antoniofilipovic**
[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by kgolubic** [comment]
@antoniofilipovic  the milestone is missing. Can you please set it?

**Comment by gitbuda** [comment]
@kgolubic this was just an experiment -> so the exact milestone is unknown 🤔 
@antoniofilipovic What's the status? How is this related to, e.g. https://github.com/memgraph/memgraph/issues/1685? 👀 
CC @Ignition

**Comment by Ignition** [comment]
#1801 Did a lot to nullify the October memory increase. But the upstream jemalloc change may still be desirable.

**Comment by antoniofilipovic** [comment]
closing PR as we are not doing it

**Pull request closed without merging**
