### PR TITLE
Add cartesian mgbench

### PR DESCRIPTION
**Pull request by Josipmrden**
Internal benchmark for cartesian product.

[master < Task] PR
- [X] Check, and update documentation if necessary
- [X] Provide the full content or a guide for the final git message

@vpavicic  internal improvement, no docs needed.

### CODE REVIEW

**Comment by vpavicic** [comment]
Please add a "docs unnecessary" label so I have a clear overview what doesn't need to be written and what somebody forgot to classify! Thank you!

**Review by as51340 — APPROVED** [review]
Does grafana need to be redoployed?

**Comment by Josipmrden** [comment]
> Does grafana need to be redoployed?

I would say no because we are just storing new identifier values to construct new graphs. It should be without downtime

**Review by antejavor — APPROVED** [review]
@Josipmrden Since we started adding workload, we should make sure @MarkoBarisic is aware of Postgress storage/size requirements. Not sure where all results are hosted, but just to keep an eye on that we are adding stuff to that instance.

**Pull request merged**
