### PR TITLE
Enable monitoring at runtime

### PR DESCRIPTION
**Pull request by Josipmrden**
Metrics will be fetched via the HTTP server on runtime if Enterprise license is enabled.

### CODE REVIEW

**Review by andrejtonev — COMMENTED** [review]
Makes sense.
However, why don't we disable it completely if not `MG_ENTERPRISE`?

**Comment by Ignition** [comment]
> Makes sense. However, why don't we disable it completely if not `MG_ENTERPRISE`?

Yeah, same thinking, why have metrics at all in the community build?

**Comment by Josipmrden** [comment]
@Ignition @andrejtonev makes sense, will disable the running of the http endpoint completely with community build!

**Review by Ignition — APPROVED** [review]

**Comment by kgolubic** [comment]
For RN I will use:

- Metrics can now be fetched via the HTTP server during runtime if a Memgraph
Enterprise license is enabled.
[#2067](https://github.com/memgraph/memgraph/pull/2067)

**Comment by Josipmrden** [comment]
Please delete either the [master < EPIC] or [master < Task] part, depending on what are your needs.

[master < Task] PR
- [x] Provide the full content or a guide for the final git message
    - **Enable monitoring of metrics at runtime**

### CI Testing Labels
Please select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [X] Add the documentation label tag
- [X] Add the bug / feature label tag
- [X] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [X] Write a release note, including added/changed clauses
    - **Monitoring can now be turned on at runtime when providing a Memgraph enterprise license**
- [X] Link the documentation PR here
    - https://github.com/memgraph/documentation/pull/806
- [X] Tag someone from docs team in the comments @kgolubic

**Pull request merged**
