### PR TITLE
Remove old flags

### PR DESCRIPTION
**Pull request by andrejtonev**
Removed deprecated flags.

--auth-module-create-missing-user
--auth-module-create-missing-role
--auth-module-manage-roles
--storage-parallel-index-recovery
--storage-recover-on-startup

### CODE REVIEW

**Comment by kgolubic** [comment]
@andrejtonev I'm missing the Release note entry and documentation PR.

**Comment by kgolubic** [comment]
I will use this as release note, and it will be marked as breaking:

- Removed deprecated command-line flags to streamline configuration and improve
  system performance. The following flags are no longer supported:
  `--storage-recover-on-startup`, `--auth-module-create-missing-user`,
  `--auth-module-create-missing-role`, `--auth-module-manage-roles`,
  `--storage-parallel-index-recovery`.
[#1916](https://github.com/memgraph/memgraph/pull/1916)

**Comment by andrejtonev** [comment]
### Description

Removed deprecated command-line flags:
```
--storage-recover-on-startup
--auth-module-create-missing-user
--auth-module-create-missing-role
--auth-module-manage-roles
--storage-parallel-index-recovery
```

- [x] Provide the full content or a guide for the final git message
    - Removed deprecated command-line flags
- [ ] Update dependent repos:
    - [ ] `mgconsole` tests under https://github.com/memgraph/mgconsole/blob/master/tests/input_output/run-tests.sh
    - [ ] `pymgclient` CI script https://github.com/memgraph/pymgclient/blob/master/.github/workflows/ci.yml
    - [ ] check other memgraph repos (mostly client libs)

### Documentation checklist
- [x] Add the documentation label tag
- [ ] Add the bug / feature label tag
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **Removed deprecated flags**
- [ ] Link the documentation PR here
    - **[Documentation PR link]**
- [ ] Tag someone from docs team in the comments

**Review by antoniofilipovic — APPROVED** [review]
Looks good

**Pull request merged**
