### PR TITLE
Support localdatetime to date and localtime transfer

### LINKED ISSUE #1372: enhance date function to support temporal type
**Describe the scenario**
we have a scenario where we store values in datetime format and we want to support day-by-day filtering and millisecond by-millisecond filtering, we use the date function like this when day-by-day filtering:
```cypher
MATCH (n:Card) WHERE n.vutId IN ['xxx']
WITH n
WHERE date(n.plan_date) = date('2023-09-30')
RETURN n
```
the "n.plan_date" is a localdatetime property, but it gets a error "Optional 'date' argument at position 1 must be either 'string' or 'map'."

### PR DESCRIPTION
**Pull request by as51340**
Closes #1372.

[master < Epic] P
- [ ] Check, and update documentation if necessary
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

**Review by andrejtonev — COMMENTED** [review]
Not much to say :D 
Can you just add an integration test that checks the exact query the user reported not working?

**Review by andrejtonev — APPROVED** [review]
:+1:

**Comment by as51340** [comment]
Changelog: `localdatetime` type can now be converted to `date` and `localtime` types.

**Comment by as51340** [comment]
Docs page https://github.com/memgraph/documentation/pull/326

**Pull request merged**
