### PR TITLE
Compile Kafka client with SASL2 enabled

### LINKED ISSUE #1031: Compile Kafka client with SASL2 enabled
All required to complete this follows:
- `libsasl2` is already installed under https://github.com/memgraph/memgraph/pull/862
-  The code change should be similar to https://github.com/memgraph/memgraph/pull/846

### PR DESCRIPTION
**Pull request by DavIvek**
closes #1031

### CODE REVIEW

**Comment by DavIvek** [comment]
Git commit description, explain the changes you made here

---
__*Leave above in PR description, copy the below into a comment*__
___


### Tracking
- [ ] **[Link to Epic/Issue]**


### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch


### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

**Review by gitbuda — CHANGES_REQUESTED** [review]
This is not enough because this change assumes that sasl2 lib is installed on the operating system level -> all supported environment scripts under https://github.com/memgraph/memgraph/tree/master/environment/os have to be changed in a way that that lib is installed as a memgraph build dependency. I'm not sure if we have to make something on the packaging side (probably not), but that has to be checked + we probably have to add a new e2e test testing that sasl connection to Kafka can be established.

**Comment by hal-eisen-MG** [comment]
Library was already added in https://github.com/memgraph/memgraph/pull/862

**Comment by hal-eisen-MG** [comment]
MEMGRAPH_BUILD_DEPS needs to have cyrus-sasl-devel (on the Red Hat derived OS's) while debian-derived need libsasl2-dev. Looks like only Fedora 38 & 39 are missing currently.

**Review by gitbuda — APPROVED** [review]
Based on the conversations, this should be enough to be able to use SASL. Maybe another concern is SSL, but SSL is also enabled under the current version of the Memgraph repo.

**Pull request merged**
