### PR TITLE
Fix a bunch of spelling mistakes (2/n)

### PR DESCRIPTION
**Pull request by jsoref**
[master < Epic] PR #1010 
- [ ] Check, and update documentation if necessary
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

**Review by gitbuda — APPROVED** [review]

**Comment by gitbuda** [comment]
> Fwiw, [0334eea](https://github.com/memgraph/memgraph/commit/0334eeaf35b4462ecd2214eed13ed6f0200524ad) would fix https://github.com/memgraph/memgraph/actions/runs/5683462072/job/15463192890
> 
> But since this is already approved, and it's really outside the scope of this PR, I'm not going to touch this PR (I'd rather trigger a CI for all files and fix them all at once..., but definitely outside these PRs which are already quite large).

Could you apply the change to this PR because applying all these changes separately is not an option because of the conflicts (this PR has much lower priority compared to the others)

**Comment by jsoref** [comment]
@gitbuda: sorry about that. I've rebased. Right now github claims there's still a conflict, but I think it'll just take github a bit to reconcile.

**Comment by jsoref** [comment]
@gitbuda: sorry about that. I've rebased.

**Comment by gitbuda** [comment]
Closing this because it's again out of sync + it's not critical.

**Pull request closed without merging**
