### PR TITLE
Added hiding sensitive informations- passwords in this case, added un…

### PR DESCRIPTION
**Pull request by tonijurjevic96**
Added string check function that checks for sensitive info

Passwords in queries are changed to asterisk (*).
Unit test is added that also check for misspelling of words to hide info in that case also.

### CODE REVIEW

**Comment by tonijurjevic96** [comment]
### Tracking
Client request


### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch


### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - Added hiding of sensitive information as an enterprise feature
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- @kgolubic

**Review by Josipmrden — APPROVED** [review]

**Comment by kgolubic** [comment]
For release note I'll use:

- Added functionality to hide sensitive information, specifically passwords, in
query logs. Passwords in queries are now masked with asterisks (`*`).
[#2140](https://github.com/memgraph/memgraph/pull/2140)

**Comment by kgolubic** [comment]
For the release note, I suggest the following:

- Added functionality to hide sensitive information, specifically passwords, in
query logs. Passwords in queries are now masked with asterisks (`*`).
[#2140](https://github.com/memgraph/memgraph/pull/2140)

**Comment by andrejtonev** [comment]
@tonijurjevic96 can we expand this to include the query itself?
`SHOW TRANSACTIONS` prints out the running query and could leak sensitive information.
see `transaction_queries_->push_back(query_string);`

**Comment by tonijurjevic96** [comment]
> @tonijurjevic96 can we expand this to include the query itself? `SHOW TRANSACTIONS` prints out the running query and could leak sensitive information. see `transaction_queries_->push_back(query_string);` cc @gitbuda

I would like to merge this than open new PR for SHOW TRANSACTIONS to make sure this enters 2.19 release

**Comment by andrejtonev** [comment]
@tonijurjevic96 sure!

**Pull request merged**
