### PR TITLE
[master < T569-FL] Allshortest bugfix

### PR DESCRIPTION
**Pull request by brunos252**
The algorithm outputted duplicated edges when used with an upper bound set to a limiting value. From changes in the code it can be seen that we should have always continued the iteration if we encountered an already expanded edge

[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [x] Check, and update documentation if necessary
- [x] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [x] Provide the full content or a guide for the final git message

### CODE REVIEW

**Comment by brunos252** [comment]
Added a test for this case. Current version of memgraph produces `count(p) = 8` because of the duplication, correct is `4`.

**Comment by brunos252** [comment]
In the commit "remove std::optional" I decided that instead of doing checks for each edge if it is not null, we can expand from the starting edge without putting it in the priority queue, and can omit the `std::optional`

**Review by antoniofilipovic — CHANGES_REQUESTED** [review]

**Comment by antoniofilipovic** [comment]
> The algorithm outputted duplicated edges when used with an upper bound set to a limiting value. From changes in the code it can be seen that we should have always continued the iteration if we encountered an already expanded edge
> 
> [master < Epic] PR
> 
> * [ ]  Check, and update documentation if necessary
> * [ ]  Update [changelog](https://docs.memgraph.com/memgraph/changelog)
> * [ ]  Write E2E tests
> * [ ]  Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
> * [ ]  Provide the full content or a guide for the final git message
> 
> [master < Task] PR
> 
> * [ ]  Check, and update documentation if necessary
> * [ ]  Update [changelog](https://docs.memgraph.com/memgraph/changelog)
> * [ ]  Provide the full content or a guide for the final git message

Also here @brunos252 , update this initial message and provide link to docs PR if needed and changelog PR so I can merge this.

**Review by antoniofilipovic — APPROVED** [review]
All seems good to go.

**Pull request merged**
