### PR TITLE
[master < T534-FL-torch-mg-load-fix] torch and igraph removing from sys cache

### PR DESCRIPTION
**Pull request by as51340**
[master < Task] PR
- [x] Check, and update documentation if necessary
- [x] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [x] Provide the full content or a guide for the final git message

- docs-changelog-message: Disable removing `torch` and `igraph` from `sys.modules` cache because of the issue occuring when reloading.
Connected issue on the PyTorch: https://github.com/pytorch/pytorch/issues/91039

### CODE REVIEW

**Comment by gitbuda** [comment]
This is unusual because 2 third-party Mage modules are ignored...

Did you consider the ability to inject the blacklist as an argument and then inject it on the Mage side since the modules are introduced there?

**Comment by as51340** [comment]
> This is unusual because 2 third-party Mage modules are ignored...
Mage modules aren't ignored, only Python packages are.
 
> Did you consider the ability to inject the blacklist as an argument and then inject it on the Mage side since the modules are introduced there?
I did but what would we get when all (re)loading is done on the core side?

**Comment by gitbuda** [comment]
Having this runtime configurable makes a lot of sense to me because Memgraph doesn't have to be recompiled if another third-party module has to be included. The only real question to me is what is the default value?

What does happen with Memgraph without the changes here? Does it crash, or what exactly happens?

**Review by antoniofilipovic — APPROVED** [review]

**Comment by vpavicic** [comment]
RN: `torch` and `igraph` can no longer be removed from the `svs.modules` cache to avoid issues after reload.

**Pull request merged**
