### PR TITLE
Add cpp23 support

### PR DESCRIPTION
**Pull request by as51340**
[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by andrejtonev** [comment]
I think this is @gitbuda - toolchain territory :smile:

**Review by Ignition — COMMENTED** [review]
Technically there is no objection in bumping C++ standard....except we are restricted by clang 13 ATM where C++23 support is very limited (as in practically nothing of C++23 is supported).

I'd rather wait until we are based on a compiler that provides a larger proportion of C++23 features + libraries.

https://en.cppreference.com/w/cpp/compiler_support/23

**Review by gitbuda — APPROVED** [review]
I think this is fine. We'll soon move to the toolchain-v5 (clang-17), let's merge this!

**Comment by as51340** [comment]
@kgolubic Support for c++23 was added for Clang 13 but then as we updated compiler to Clang 17, we found a bug in the compiler so standard is reverted to c++20. I would just skip this in the release notes.

**Pull request merged**
