### PR TITLE
Add unique constraints capability of serving as indices

### PR DESCRIPTION
**Pull request by Josipmrden**
Users sometimes insert unique constraints without label property indices. Unique constraints have the same data structure and can be used if no indices present as indexed scan.

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by andrejtonev** [comment]
Hey @Josipmrden would love to jump on a call when you have the time.
Before I do a proper review, I would need some help in understanding what is actually going on.

**Comment by antejavor** [comment]
Make this work :D  cc @Josipmrden 

```
// NO index no uniqueness/exist constraint 
UNWIND range(1, 500000) AS id 
CREATE (:Node {ID: id})

UNWIND range(1, 100) AS id 
MATCH (a:Node{ID: id}) 
MATCH (b:Node {ID: id})  
CREATE (a)-[:RELATIONSHIP]->(b)
//Result: 19 seconds
//Expected


// Exist constraint after creating data
UNWIND range(1, 500000) AS id 
CREATE (:Node {ID: id})

CREATE CONSTRAINT ON (n:Node) ASSERT EXISTS (n.ID);

UNWIND range(1, 100) AS id 
MATCH (a:Node{ID: id}) 
MATCH (b:Node {ID: id})  
CREATE (a)-[:RELATIONSHIP]->(b)
// Result: 19 seconds
// Unexpected, this is a constraint, maybe data structure was not ready in run? 

// Before creating data 
CREATE CONSTRAINT ON (n:Node) ASSERT EXISTS (n.ID);
UNWIND range(1, 500000) AS id 
CREATE (:Node {ID: id})

UNWIND range(1, 100) AS id 
MATCH (a:Node{ID: id}) 
MATCH (b:Node {ID: id})  
CREATE (a)-[:RELATIONSHIP]->(b)
//Result: 19 seconds 
// Unexpected, maybe this works only on uniqueness constraint


//Unniqness constraint 
CREATE CONSTRAINT ON (n:Node) ASSERT n.ID IS UNIQUE;
UNWIND range(1, 500000) AS id 
CREATE (:Node {ID: id})

UNWIND range(1, 100) AS id 
MATCH (a:Node{ID: id}) 
MATCH (b:Node {ID: id})  
CREATE (a)-[:RELATIONSHIP]->(b) 
//Result: 19 seconds 
// Unexpected, this is should work
```

**Comment by kgolubic** [comment]
This will be the Release note:

- Added the capability for unique constraints to serve as indices. This
enhancement allows unique constraints to be used for indexed scans if no label
property indices are present, optimizing query performance.
[#1356](https://github.com/memgraph/memgraph/pull/1356)

**Comment by hal-eisen-MG** [comment]
Can we close this?

**Comment by Josipmrden** [comment]
Closing until further notice.

**Pull request closed without merging**
