### PR TITLE
Remove graphql e2e tests

### PR DESCRIPTION
**Pull request by antoniofilipovic**
Removing graphql as agreed

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by as51340** [comment]
I have already removed this in my pr...

**Comment by antoniofilipovic** [comment]
> I have already removed this in my pr...

Can you approve this one so this is explicitly done?

**Comment by as51340** [comment]
That should get merged before this one I think. Plus, they were commented (I think no reason for commenting) so this doesn't actually change anything since tests weren't executed

**Comment by antoniofilipovic** [comment]
Closed as will be removed in new PR

**Pull request closed without merging**
