### PR TITLE
Rename HA flags for cluster setup

### PR DESCRIPTION
**Pull request by as51340**
### Description

Renamed flags used when setting up HA cluster.

[master < Task] PR
- [x] Provide the full content or a guide for the final git message
    - **Rename flags for setting up HA cluster**

### Documentation checklist
- [x] Add the documentation label tag
- [x] Add the bug / feature label tag
- [x] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [x] Write a release note, including added/changed clauses
    - **[Release note text]**
- [ ] Link the documentation PR here
    - **[Documentation PR link]**
- [x] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by as51340** [comment]
@kgolubic docs will be added in batch before 10th April, will post link then.

release note: Renamed HA flags to improve cluster setup

**Review by antoniofilipovic — COMMENTED** [review]
This looks good. Do we want to rename also other structs? RaftState -> CoordinatorState, CoordinatorInstance -> ManagementInstance?

**Comment by as51340** [comment]
We already have CoordinatorState.
CoordinatorInstance sounds better than ManagementInstance to me

**Comment by antoniofilipovic** [comment]
> We already have CoordinatorState. CoordinatorInstance sounds better than ManagementInstance to me

I forgot about CoordinatorState. We will be inconsistent then, I am not sure if that is good. We can then rename current CoordinatorState to something, and RaftState to CoordinatorState.

What do you think?

**Review by antoniofilipovic — APPROVED** [review]

**Pull request merged**
