### PR TITLE
Fix unit/coordinator_cluster_setup

### PR DESCRIPTION
**Pull request by as51340**
### Description

Unit test failed because registration occasionally failed since replica was registered before it was fully up. The fix consists of iterative registration until it succeeds (max 5 times).

[master < Task] PR
- [x] Provide the full content or a guide for the final git message
    - **Fix unit/coordinator_cluster_setup**

### Documentation checklist
- [x] Add the documentation label tag
- [x] Add the bug / feature label tag
- [x] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[Release note text]**
- [] Link the documentation PR here
    - **[Documentation PR link]**
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by as51340** [comment]
@kgolubic RN not needed, internal fix

**Review by antoniofilipovic — COMMENTED** [review]
Why was this failling did you find the bug?

**Comment by as51340** [comment]
> Why was this failing did you find the bug?

Written in the PR description

**Comment by antoniofilipovic** [comment]
I wanted to ask why is fix that we need to try to register it 5 times, what if it starts being flaky again because fix was to start it after 6 times

**Comment by as51340** [comment]
> I wanted to ask why is fix that we need to try to register it 5 times, what if it starts being flaky again because fix was to start it after 6 times

I understand what you mean but there always needs to be some max attempts number. I chose 5, don't see an issue?

**Pull request closed without merging**
