### PR TITLE
Removing obsolete files as per Deda's suggestion

### PR DESCRIPTION
**Pull request by hal-eisen-MG**
Removing files we don't use any more

Removing deprecated publish-to-dockerhub workflow
Removing oldest Linux distros
Removing toolchain v4 files

### CODE REVIEW

**Comment by hal-eisen-MG** [comment]
### Tracking
- [ ] **[Link to Epic/Issue]**


### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch


### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

**Comment by hal-eisen-MG** [comment]
See also https://www.notion.so/memgraph/Deprecated-files-10e6b158b98180c4aae2f5047629eabc

**Comment by kgolubic** [comment]
If Toolchain v4 files are removed the documentation page https://memgraph.com/docs/getting-started/build-memgraph-from-source will probably also need an update.

**Review by gitbuda — APPROVED** [review]
Deleting stuff is always good 💪

**Comment by hal-eisen-MG** [comment]
Regarding Kruno's suggestion, there is a commit in the documentation PR for memgraph-2-21 to sync with this PR here

**Pull request merged**
