### PR TITLE
Isolate cursor.hpp

### PR DESCRIPTION
**Pull request by gitbuda**
Not the whole `operator.hpp` is required if we want to introduce a new cursor.

### CODE REVIEW

**Comment by Ignition** [comment]
ATM all the `*Operator::MakeCursor`'s are in operator.hpp
What is the motivation to split this part out? Are Operators doing to be split up as well soon?

**Comment by andrejtonev** [comment]
Are there any files that should change the file included?

**Comment by gitbuda** [comment]
@Ignition I'm experimenting under https://github.com/gitbuda/memgraph/pull/12, each cursor there has a standalone cpp file (ofc if possible) -> this was just the smallest chunk of work which seems to be useful 🤔 
@andrejtonev -> Including `cursor.hpp` is not needed since `operator.hpp` and everything else includes the operator. When and if we decouple more, additional includes might get required 👀

**Comment by hal-eisen-MG** [comment]
Can we close this?

**Comment by gitbuda** [comment]
I think useful, but got in conflict + it's easy to redo if needed -> closing this PR

**Pull request closed without merging**
