### PR TITLE
[master < T982] Add mgp any type to C++ query module wrapper

### PR DESCRIPTION
**Pull request by Josipmrden**
This is a C++ query module enhancement that allows users to write C++ query modules with arguments of variable type. So far only C API was able to do this, and the wrapper did not account for the Any type. This is an extension that allows for this misalignment.

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [x] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [X] Write a release note here 
You are now able to use `mgp::Type::Any` in C++ query modules to specify that the argument of the query modules can be of any type.

- [X] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by Josipmrden** [comment]
@vpavicic I'll begin docs update shortly

**Review by antoniofilipovic — APPROVED** [review]
Looks good

**Comment by vpavicic** [comment]
`init-file` and `init-data-file` configuration flags allow the execution of queries from the CYPHERL prior to or immediately after the Bolt server starts and are now available in the Community Edition.

@Josipmrden ok?

**Comment by vpavicic** [comment]
ou can now use `mgp::Type::Any` while developing a custom query procedure
  with the C++ API to specify that the argument of the procedure can be of any
  type.
  
  @Josipmrden  oK?

**Pull request merged**
