### PR TITLE
[master < T1249] Add Path.pop to C++ API

### PR DESCRIPTION
**Pull request by imilinovic**
There was a need to be able to remove the last element of a path in the C++, C and Python API.

[master < Task] PR
- [x] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [X] Write a release note here, including added/changed clauses
You are now able to remove the last element of a path in C++ (path.Pop()) , C (mgp_path_pop) and Python (path.pop()) API
- [x] Tag someone from docs team in the comments

### CODE REVIEW

**Review by antepusic — COMMENTED** [review]
This looks good. I think that it makes sense to add a corresponding method to the Python API as well.

**Review by antepusic — APPROVED** [review]

**Comment by imilinovic** [comment]
@vpavicic [Docs PR](https://github.com/memgraph/documentation/pull/184)

**Review by antoniofilipovic — APPROVED** [review]
Looks good to me

**Comment by antoniofilipovic** [comment]
@imilinovic please link PR on which we need it on MAGE side, and on MAGE also add backlink to this PR

**Comment by imilinovic** [comment]
Used in:
[MAGE-PR356](https://github.com/memgraph/mage/pull/356)

**Pull request merged**
