### PR TITLE
Remove noexcept from functions that may throw

### PR DESCRIPTION
**Pull request by antepusic**
This PR fixes Memgraph crashing when a user’s query procedure attempts to construct a `LocalDateTime` object with invalid parameters
A C++ API `LocalDateTime` object is built upon a `memgraph::utils::LocalDateTime` object, which has a constructor that’s a) noexcept b) constructs a `memgraph::utils::Date` member, which may throw an exception
This error has been fixed together with other `LocalDateTime` constructors that were marked as noexcept but might throw an exception
[master < Task] PR
- [x] Check, and update documentation if necessary
- [x] Provide the full content or a guide for the final git message
> Fix Memgraph crashing when constructing mgp::LocalDateTime objects with invalid parameters

To keep docs changelog up to date, one more thing to do:
- [x] Write a release note here
> Constructing LocalDateTime objects with invalid parameters doesn’t crash Memgraph anymore, but throws an informative exception.
- [x] Tag someone from docs team in the comments

### CODE REVIEW

**Comment by antepusic** [comment]
@vpavicic The release note is in the initial comment

**Review by Josipmrden — APPROVED** [review]

**Review by jbajic — APPROVED** [review]

**Review by antoniofilipovic — APPROVED** [review]

**Comment by antoniofilipovic** [comment]
@antepusic write a release note here. @vpavicic

**Comment by Josipmrden** [comment]
@antepusic @antoniofilipovic  can this go in the release?

**Comment by antoniofilipovic** [comment]
@Josipmrden yes, I will merge this.

**Pull request merged**
