### PR TITLE
[master < ] Add cypherl transform script

### PR DESCRIPTION
**Pull request by gitbuda**
[master < Task] PR
- [x] Enhance the user experience, mostly colors!
- [x] Implement the test script and test the script 😂
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

--> Here we can merge

- [x] Test with `mgconsole` batch import mode

### CODE REVIEW

**Comment by katarinasupe** [comment]
Consider adding a potential fix for the issue https://github.com/memgraph/memgraph/issues/612 also here.

**Comment by gitbuda** [comment]
> Consider adding a potential fix for the issue #612 also here.

I think #612 is a different concern, so I will merge this as is. We'll close/resolve #612 issue at a different place.

**Comment by katarinasupe** [comment]
@gitbuda do you remember if you used any [specific options](https://neo4j.com/labs/apoc/4.1/export/cypher/#export-cypher-config) for export to obtain the cypherl file?

**Comment by katarinasupe** [comment]
`{format: "plain"}` works, without it mgconsole prints the following error:
`Client received query exception: Index manipulation not allowed in multicommand transactions.`

Neither works in Memgraph Lab (cypherl import). This is an error if no config is provided:
`Invalid automatic transaction context: There is a transaction handler command BEGIN; within the query list. If you wish to create a manual transaction context, start with a BEGIN and end the query list with a COMMIT or a ROLLBACK.`
This is the error if plain format config is provided: 
Query should either create or update something, or return results!

**Comment by katarinasupe** [comment]
It is not working as fast as expected. The issue happens because of indexes. Besides indexes for every label/node (or instead), \`UNIQUE IMPORT LABEL\`(\`UNIQUE IMPORT ID\`) index should be created for faster import. Example query in exported cypherl:

```
CREATE (:Driver`:UNIQUE IMPORT LABEL` {id:"D_1035", name:"Driver_19", status:"off-duty", `UNIQUE IMPORT ID`:0});
````

When I added CREATE INDEX ON :\`UNIQUE IMPORT LABEL\`(\`UNIQUE IMPORT ID\`) line before relationship import, it speeds up.

**Comment by katarinasupe** [comment]
> `{format: "plain"}` works, without it mgconsole prints the following error: `Client received query exception: Index manipulation not allowed in multicommand transactions.`
> 
> Neither works in Memgraph Lab (cypherl import). This is an error if no config is provided: `Invalid automatic transaction context: There is a transaction handler command BEGIN; within the query list. If you wish to create a manual transaction context, start with a BEGIN and end the query list with a COMMIT or a ROLLBACK.` This is the error if plain format config is provided: `Query should either create or update something, or return results! `

This happens because without `{format: "plain"}` option, everything is wrapped in begin and commit and in the script, these are just translated into Memgraph BEGIN and COMMIT which is not okay in index and/or Memgraph Lab case.

**Pull request merged**
